# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scor.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QInputDialog
import sys


class scor_UI(QMainWindow):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setStyleSheet("border-image: url(:/newPrefix/3.qrc);")

        self.label_defen = QtWidgets.QLabel(Form)
        self.label_defen.setGeometry(QtCore.QRect(80, 20, 58, 16))
        self.label_defen.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 80, 58, 16))
        self.label_2.setObjectName("label_2")

        self.lineEdit_defen = QtWidgets.QLineEdit()

        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(80, 180, 58, 16))
        self.label_3.setObjectName("label_3")

        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(150, 20, 111, 22))
        self.spinBox.setObjectName("spinBox")

        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(150, 70, 271, 74))
        self.textEdit.setObjectName("textEdit")

        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(150, 180, 271, 74))
        self.textEdit_2.setObjectName("textEdit_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "评分表"))
        self.label_defen.setText(_translate("Form", "得分"))
        self.label_2.setText(_translate("Form", "自我评价"))
        self.label_3.setText(_translate("Form", "录入错题图片"))
import 3_rc
